Algoritmo "Soma"

Var
   x, y, s : inteiro

Inicio
   escreval("Digite o valor de x:")
   escreva("> ")
   leia(x)
   
   escreval("Digite o valor de y:")
   escreva("> ")
   leia(y)
   
   s <- (x+y)
   
   escreval
   escreval("A soma entre", x, " e",y, " é:", s)
   // O espaço entre os caracteres e as variáveis é automático para variáveis
   // depois dos caracteres


Fimalgoritmo